# This has been stoled from below:
#  here https://docs.travis-ci.com/user/languages/python/

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r test/requirements.txt requirements.txt

script:
  - pytest test/
